### ISSUE TITLE
How do I change the fonts?

### ISSUE THREAD

**Issue by BobWalsh** [noxify/gridsome-starter-casper-v3#1]
Currently, you're using system-ui for headers, Georgia for body. I want to change this, but can't find where these fonts are defined/configured.

**Comment by noxify** [comment]
Hi @BobWalsh 

I‘m using the tailwindcss default fonts and have added some classes to change the fonts for some elements. 

If you need to change it, please check the tailwindcss documentation :)

Hope that helps.

Regards,
Marcus
